version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: postgres_cdc
    environment:
      POSTGRES_USER: levi
      POSTGRES_PASSWORD: levi
      POSTGRES_DB: levicdc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
